// Type declarations for JSON files generated by scripts/build-index.ts.
// The actual files live in src/generated/ (gitignored).
// Run `npm run prebuild` to create them before building or starting dev.

declare module '*/incidents-all.json' {
  import type { Incident } from '../schema/incident'
  const data: Incident[]
  export default data
}

declare module '*/incidents-index.json' {
  import type { Incident } from '../schema/incident'
  const data: Incident[]
  export default data
}
